//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.29 at 12:56:03 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schema.healthcare.com/enrollees/pojo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.healthcare.schema.enrollees.pojo;
